# Generated by Django 6.0.6 on 2026-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500, unique=True)),
                ('published_at', models.DateTimeField()),
                ('summary', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='FeedItem',
        ),
    ]
