# Generated by Django 6.0.6 on 2026-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_hilarious_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.FileField(blank=True, help_text='Upload cover image', null=True, upload_to='blog_covers/'),
        ),
    ]
