# Generated by Django 6.0.6 on 2026-07-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_dailyemailcounter_subscriber_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyEmailCounter',
        ),
        migrations.RemoveIndex(
            model_name='emailnotificationqueue',
            name='subscribers_status_20dac1_idx',
        ),
        migrations.DeleteModel(
            name='EmailNotificationQueue',
        ),
    ]
